logging:
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        root: WARN
        com.example.demo: debug
        org.springframework.web: WARN
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
server:
    address: localhost
    port: 80

spring:
    output:
    ansi:
        enabled: DETECT

    datasource:
        username: test
        password: test
        url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        sql-script-encoding: UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 20000
            idle-timeout: 300000
            max-lifetime: 1200000
            maximum-pool-size: 10
            minimum-idle: 5
    jpa:
        database: mysql
        database-platform:  org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                enable_lazy_load_no_trans: true
                format_sql: true
        show-sql: true